/*
//Reason : “BeaconHS1Migration” : Inactivated the completed class , as this is not needed for LH Product.
//By : Mahesh Bogila , 7/3/2019
*/
//public class ATVContentSetupCaseSchedule implements Schedulable {
public class ATVContentSetupCaseSchedule 
{
    Integer i1 = 1; 
    Integer i2 = 1; 
    Integer i3 = 1; 
    Integer i4 = 1; 
    Integer i5 = 1; 
    Integer i6 = 1; 
    Integer i7 = 1; 
    Integer i8 = 1; 
    Integer i9 = 1; 
    Integer i10 = 1; 
    /*
    public void execute(SchedulableContext sc) {
        ATVContentSetupCaseBatch b = new ATVContentSetupCaseBatch();
        database.executebatch(b, 50);
    }*/
}