/*
//Reason : “BeaconHS1Migration” : Inactivated the completed class , as this is not needed for LH Product.
//By : Mahesh Bogila , 7/3/2019

/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 26-Dec-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 26-Dec-2018
  Description ........: Class contains invocable method to call CTS Sync Service method to update 
  relative object record CTS Ticket Reference information
*****************************************************************************/
public class CTSTicketIdSync
{
    Integer i1 = 1; 
    Integer i2 = 1; 
    Integer i3 = 1; 
    Integer i4 = 1; 
    Integer i5 = 1; 
    Integer i6 = 1; 
    Integer i7 = 1; 
    Integer i8 = 1; 
    Integer i9 = 1; 
    Integer i10 = 1; 
   /* @InvocableMethod
    public static void UpdateRelatedObjectData(List<Id> objectIds)
    {
        try
        {
            if(objectIds.size() > 0){
            
                CTSSyncService.UpdateSFDCObject(objectIds);
            }
        }
        catch(Exception e)
        {
            System.Debug('An error occurred: ' + e);
        }
    }*/
}