/************************************************************************************************
*Name: Mahesh Bogila
*Jira: https://jira.registeredsite.com/browse/TEAM-39179
*Purspose: Schedule Class for the Batch Class ChildAccLiveController
************************************************************************************************/
global class ScheduleChildAccLiveController implements Schedulable
{
 
    global void execute(SchedulableContext sc) 
    {/*

        ChildAccLiveController b1 = new ChildAccLiveController();
        ID batchprocessid = Database.executeBatch(b1,200);  
        */         
    }


}