/*
//Reason : “BeaconHS1Migration” : Inactivated the complete class , as this is not needed for LH Product.
//By : Mahesh Bogila , 7/3/2019
//*/
global class SEOAuditCaseJob //implements Schedulable 
{
	
    Integer i1 = 1; 
    Integer i2 = 1; 
    Integer i3 = 1; 
    Integer i4 = 1; 
    Integer i5 = 1; 
    Integer i6 = 1; 
    Integer i7 = 1; 
    Integer i8 = 1; 
    Integer i9 = 1; 
    Integer i10 = 1; 
    /*global void execute(SchedulableContext sc) {
		System.debug('SCHEDULE JOB');
		SEOAuditCaseBatch b = new SEOAuditCaseBatch();
		Database.executebatch(b);
	}*/
}