@isTest 
private class testCreateAssetonClosedWon {
  
  /*static testMethod void testCreateAssetonClosedWon(){
    
    Account a = [select Id from Account limit 1];
    PricebookEntry pbID = [select Id from PricebookEntry limit 1];
    Opportunity o = new Opportunity();
    OpportunityLineItem ol = new OpportunityLineItem();
    
    o.AccountId = a.Id;
    o.RecordTypeId = '012600000009YRTAA2';
    o.Name = 'test';
    o.StageName =  'New Opportunity';
    o.CloseDate = date.today();
    o.Contract_Term_in_months__c = 12;
    o.Renewal_Term_in_months__c = 12;
    o.Products__c = 'PPC';
    insert o;
    
    ol.OpportunityId = o.Id;
    ol.Quantity = 1;
    ol.UnitPrice = 2.00;
    ol.PricebookEntryId = pbId.Id;
    
    insert ol;
    
    o.StageName= 'Closed Won';
    o.Contract_Auto_Created__c = True;
    update o;
    
    delete ol;
    delete o;
    
    
    
  }*/
  
  
}