@isTest
/************************************************************************************************
*Name: Mahesh Bogila
*Jira: https://jira.registeredsite.com/browse/TEAM-39179
*Purspose: Test class for Schedule Class for the Batch Class ChildAccLiveController
************************************************************************************************/
public class Test_SheduleChildAccLiveCont 
{
  public static testMethod void testschedule() 
  {/*
      Test.StartTest();
      
      ScheduleChildAccLiveController sh1 = new ScheduleChildAccLiveController();
      String sch = '0 00 00 * * ?'; 
      system.schedule('Test Schedule ChildLive', sch, sh1); 
      
      Test.stopTest(); 
      */
   }
 
}