/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 21-Jun-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 21-Jun-2018
  Description ........: Schedulable class to execute batch wbnNationalNCSStatusNotificationBatch on a daily schedule.
*****************************************************************************/
public class wbnNationalNCSStatusNotificationSchedule Implements Schedulable {

  public void execute(SchedulableContext sc) {
  
    
    
  }
  
}